import './js/getTrendFilm';
import './js/getGenres';
import './js/getFilmByKeywords';
import './js/pagination'
import './js/galleryMarkup';
import './js/modalFilmMarkup';
import './js/modal-team/modal-team';
import './js/localStorage';
import './js/theme';
import './js/modal-login';
import './js/scroll-up';
