import './js/getTrendFilm';
import './js/getGenres';
import './js/getFilmByKeywords';
import './js/pagination';
import './js/galleryMarkup';
import './js/modalFilmMarkup';
import './js/modal-team/modal-team';
import './js/localStorage';
import './js/theme';
import './js/modal-login';
import './js/translation/translate';
import './js/scroll-up';
import './js/creatingSlider';
import './js/firebase/firebase-initialize';
import './js/movie-trailer'
import './js/scrollShow';
